### ISSUE TITLE
Bioconda version soon available

### ISSUE THREAD

**Issue by mfansler** [bnprks/BPCells#241]
We have [merged a Bioconda recipe for `BPCells`](https://github.com/bioconda/bioconda-recipes/pull/55118) under the package name `r-bpcells`. It should be available within a few hours of this post.

## Usage
Whenever using `bioconda` channel one must always have `conda-forge` set to a higher priority. For basic *ad hoc* installation, one can use the command:

**Minimal install**
```bash
conda install -c conda-forge -c bioconda r-bpcells
```

However, typical usage will likely want `Suggests` packages as well. I would strongly recommend using a dedicated environment. An *ad hoc* command would look something like:

**Fuller install**
```bash
conda create -n bpcells_r44 -c conda-forge -c bioconda \
  r-base=4.4 \
  r-bpcells \
  bioconductor-genomicranges \
  bioconductor-iranges \
  r-igraph \
  r-matrixstats \
  r-rspectra \
  macs3
```

Even better practice is to use a YAML to define the environment:

**bpcells_0_3_0.yaml**
```yaml
name: bpcells_0_3_0
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - r-base=4.4
  - r-bpcells=0.3.0
  - bioconductor-genomicranges
  - bioconductor-iranges
  - r-igraph
  - r-matrixstats
  - r-rspectra
  - macs3
```

**Install command**
```bash
conda env create -n bpcells_0_3_0 -f bpcells_0_3_0.yaml
```

---

Please feel free to post Issues with the Bioconda package on https://github.com/bioconda/bioconda-recipes/issues and don't hesitate to ping me.
