### ISSUE TITLE
Submit to CRAN or CONDA

### ISSUE THREAD

**Issue by shahrozeabbas** [bnprks/BPCells#51]
Hi,

Was just curious if there was a plan to upload to CRAN with the release of Seuratv5? I know these are independent packages, but since Seurat v5 depends on BPCells, would be nice to install via CRAN or CONDA. 

Thanks 🙂

**Comment by bnprks** [comment]
Good question -- yes, it is planned to release BPCells through CRAN but it will probably be a little while (I'd estimate 2-3 months). There are a couple technical changes to the compiled code in order to meet CRAN's portability requirements, and first-time CRAN submissions also have pretty stringent documentation requirements such as examples for every public function.

I don't have a plan for conda release right now, though could be convinced to do so by someone with experience releasing R packages in conda.

I'll also mention that BPCells has some pre-built packages for Windows, Mac, and Ubuntu Jammy available through [R-universe](https://bnprks.r-universe.dev/BPCells). I don't actively check that these builds are working, but they should automatically track the github main branch and help skip C++ compilation time during install.

**Comment by ycli1995** [comment]
Hi, @bnprks and @shahrozeabbas,

  I agree that it would be expected that `BPCells` can be submitted to CRAN. 

  I'm currently trying to build an R package to provide some sub-classes of `SingleCellExperiment` where `assays` would depend on  BPCells matrices to store single-cell data. In my experiences, `IterableMatrix` backed on disk files performs better than `DelayedArray` on IO and most matrix mathematics. I can see that some day more excellent features would work for BPCells, such as holding project metadata along with it, and interoperation between `SingleCellExperiment`, `SeuratObject`, `AnnData` and so on. Therefore, it would be definitely apprecitated that BPCells can become an generally accessible dependency package for R community.

**Comment by mainyanghr** [comment]
very frustrating to install this package and spend for several days and still did not work on M1 Mac.

**Comment by shahrozeabbas** [comment]
@bnprks Yeah I think you're right, don't believe there is any automated connection for it. I agree though, CRAN may be more useful. 

If I am able to submit something to Anaconda in R, I will be sure to reach out.

**Comment by rschauner** [comment]
> Good question -- yes, it is planned to release BPCells through CRAN but it will probably be a little while (I'd estimate 2-3 months). There are a couple technical changes to the compiled code in order to meet CRAN's portability requirements, and first-time CRAN submissions also have pretty stringent documentation requirements such as examples for every public function.
> 
> I don't have a plan for conda release right now, though could be convinced to do so by someone with experience releasing R packages in conda.
> 
> I'll also mention that BPCells has some pre-built packages for Windows, Mac, and Ubuntu Jammy available through [R-universe](https://bnprks.r-universe.dev/BPCells). I don't actively check that these builds are working, but they should automatically track the github main branch and help skip C++ compilation time during install.

I was able to get a working conda binary (for Linux only) using the following set of files and running `conda build` and uploaded it to [Anaconda](https://anaconda.org/rschauner/r-bpcells).

<details>

<summary>meta.yaml</summary>

```yaml
{% set version = 'v0.1.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-bpcells
  version: {{ version|replace("-", "_") }}

source:
  git_rev: {{ version }}
  git_url: https://github.com/bnprks/BPCells.git

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  # no skip

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]


  host:
    - r-base >=4.3
    - r-rcpp>=1.0.7
    - r-magrittr
    - r-matrix
    - r-rlang
    - r-vctrs
    - r-stringr
    - r-tibble
    - r-dplyr
    - r-tidyr
    - r-ggplot2
    - r-scales
    - r-patchwork
    - r-scattermore
    - r-ggrepel
    - r-rcolorbrewer
    - r-hexbin
    - r-rcppeigen
    - hdf5


  run:
    - r-base >=4.3
    - {{native}}gcc-libs         # [win]
    - r-rcpp>=1.0.7
    - r-magrittr
    - r-matrix
    - r-rlang
    - r-vctrs
    - r-stringr
    - r-tibble
    - r-dplyr
    - r-tidyr
    - r-ggplot2
    - r-scales
    - r-patchwork
    - r-scattermore
    - r-ggrepel
    - r-rcolorbrewer
    - r-hexbin
    - r-rcppeigen


test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('BPCells')"           # [not win]
    - "\"%R%\" -e \"library('BPCells')\""  # [win]


about:
  home: https://bnprks.github.io/BPCells/index.html
  summary: Efficient operations for single cell ATAC-seq fragments and
    RNA counts matrices. Interoperable with standard file formats, and introduces
    efficient bit-packed formats that allow large storage savings and increased
    read speeds.
  license: MIT
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'

```
</details>

<details>

<summary>build.sh</summary>

```bash
#!/bin/bash

# 'Autobrew' is being used by more and more packages these days
# to grab static libraries from Homebrew bottles. These bottles
# are fetched via Homebrew's --force-bottle option which grabs
# a bottle for the build machine which may not be macOS 10.9.
# Also, we want to use conda packages (and shared libraries) for
# these 'system' dependencies. See:
# https://github.com/jeroen/autobrew/issues/3
export DISABLE_AUTOBREW=1

# R refuses to build packages that mark themselves as Priority: Recommended
mv DESCRIPTION DESCRIPTION.old
grep -va '^Priority: ' DESCRIPTION.old > DESCRIPTION
# shellcheck disable=SC2086
${R} CMD INSTALL --build . ${R_ARGS}
```

</details>

<details>

<summary>build.bat</summary>

```bat
"%R%" CMD INSTALL --build . %R_ARGS%
IF %ERRORLEVEL% NEQ 0 exit /B 1
```

</details>
